// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SemanticKernelExample01.Context;

#nullable disable

namespace SemanticKernelExample01.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241107031205_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SemanticKernelExample01.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Food",
                            Description = "Long-grain rice with a light texture, ideal for curries and Asian cuisine. Its natural fragrance and fluffy grains make it perfect for side dishes and fresh salads.",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFB9BUTloCAxUTEZkX73j2cz7sp7nZFWx1KQ&s",
                            Name = "Premium Basmati Rice",
                            Price = 10.99m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Food",
                            Description = "Cold-pressed olive oil with a smooth, fruity flavor. Ideal for dressings, marinades, and as a finishing touch for Mediterranean dishes. No additives, 100% natural.",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFB9BUTloCAxUTEZkX73j2cz7sp7nZFWx1KQ&s",
                            Name = "Artisanal Extra Virgin Olive Oil",
                            Price = 10.99m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Food",
                            Description = "Soy sauce made with reduced salt for authentic flavor without excess sodium. Perfect for adding an Asian touch to stir-fries, marinades, and sauces.",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFB9BUTloCAxUTEZkX73j2cz7sp7nZFWx1KQ&s",
                            Name = "Low-Sodium Soy Sauce",
                            Price = 10.99m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Food",
                            Description = "Premium cut of Angus beef selected for its marbling and intense flavor. Ideal for grilling and barbecues, with a juicy cook and tender texture.",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFB9BUTloCAxUTEZkX73j2cz7sp7nZFWx1KQ&s",
                            Name = "Angus Beef for Grilling",
                            Price = 10.99m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Food",
                            Description = "Blend of walnuts, almonds, cranberries, and raisins. A healthy snack option, ideal for pairing with yogurt or salads, with no added sugars.",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFB9BUTloCAxUTEZkX73j2cz7sp7nZFWx1KQ&s",
                            Name = "Gourmet Mixed Nuts",
                            Price = 10.99m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Food",
                            Description = "Italian Parmesan aged for 24 months, with a strong flavor and crumbly texture. Perfect for grating over pasta, salads, and risottos.",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFB9BUTloCAxUTEZkX73j2cz7sp7nZFWx1KQ&s",
                            Name = "Parmigiano Reggiano Cheese",
                            Price = 10.99m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Food",
                            Description = "Colombian coffee with a medium roast, offering a balanced flavor with fruity notes. Ideal for French press or espresso preparations, delivering an authentic experience.",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFB9BUTloCAxUTEZkX73j2cz7sp7nZFWx1KQ&s",
                            Name = "Premium Colombian Coffee Beans",
                            Price = 10.99m
                        },
                        new
                        {
                            Id = 8,
                            Category = "Food",
                            Description = "Cold-smoked salmon with a delicate texture and flavor. Ideal for bagels, salads, or enjoying solo with a squeeze of lemon.",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFB9BUTloCAxUTEZkX73j2cz7sp7nZFWx1KQ&s",
                            Name = "Smoked Salmon Fillets",
                            Price = 10.99m
                        },
                        new
                        {
                            Id = 9,
                            Category = "Food",
                            Description = "Raw, unfiltered honey harvested from wildflowers. Rich in antioxidants, it’s ideal for sweetening drinks, dressings, and baking recipes.",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFB9BUTloCAxUTEZkX73j2cz7sp7nZFWx1KQ&s",
                            Name = "Organic Honey",
                            Price = 10.99m
                        },
                        new
                        {
                            Id = 10,
                            Category = "Food",
                            Description = "Special vintage Malbec with intense flavor and notes of red fruits and spices. Ideal to pair with red meats, cheeses, and pasta.",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFB9BUTloCAxUTEZkX73j2cz7sp7nZFWx1KQ&s",
                            Name = "Malbec Reserva Red Wine",
                            Price = 10.99m
                        },
                        new
                        {
                            Id = 11,
                            Category = "Food",
                            Description = "Flour made from organically grown whole wheat, perfect for healthy baking and pastry recipes. Provides more fiber and flavor than traditional white flour.",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFB9BUTloCAxUTEZkX73j2cz7sp7nZFWx1KQ&s",
                            Name = "Organic Whole Wheat Flour",
                            Price = 10.99m
                        },
                        new
                        {
                            Id = 12,
                            Category = "Food",
                            Description = "Japanese-origin matcha green tea powder, rich in antioxidants and perfect for preparing drinks, smoothies, or desserts with a natural energy boost.",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFB9BUTloCAxUTEZkX73j2cz7sp7nZFWx1KQ&s",
                            Name = "Matcha Green Tea Powder",
                            Price = 10.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
